Display locations on conference list
tighten/symposium pull request #532
Opened 2024-12-20 20:04 UTC by andrewmile

This PR closes #519 by adding the conference location to the conferences list page. This PR also adds a `app:backfill-conference-location-names` to backfill a display-friendly conference location. Each conference listing will then display either the conference's location name, or the value in the `location` column, if present.

<img width="482" alt="image" src="https://github.com/user-attachments/assets/ffc54ed7-77ad-4105-b090-8bf88739d35a" />

2025-01-06 16:27 UTC, mattstauffer requested changes

2025-01-06 16:27 UTC, mattstauffer commented on app/CallingAllPapers/ConferenceImporter.php
> +        if ($conference->location) {
It's probably worth adding a test to ensure `geocodeLocation` isn't called if latitude and longitude or set, so this isn't every accidentally broken in the future.

2025-01-06 16:27 UTC, mattstauffer commented on app/Console/Commands/BackfillConferenceLocationNames.php
> +    protected $description = 'Command description';
Please fill out

2025-01-17 20:28 UTC, andrewmile commented on app/CallingAllPapers/ConferenceImporter.php
> +        if ($conference->location) {
My initial thinking was that we'd want to geocode the location whether or not we already have the coordinates so we can get the location name but you're right that this would cause additional requests. This PR already falls back to the location from CFP, which is mostly `city, country` anyway so I reverted this line.

I also added a commit for the frontend to capture the location name when creating a conference since we have that data available from the google maps API anyway.

2025-01-17 20:28 UTC, andrewmile commented on app/Console/Commands/BackfillConferenceLocationNames.php
> +    protected $description = 'Command description';
Done

2025-01-17 20:29 UTC, andrewmile commented on app/CallingAllPapers/ConferenceImporter.php
> +        if ($conference->location) {
I also added test coverage here to ensure we don't call the geocoder when we already have lat/lng.

2025-01-17 20:32 UTC, andrewmile commented on app/Services/Geocoder.php
> +    public function geocode(string $address): self
I went down the path of turning the `geocode` method into a static constructor but the usage felt clunky in tests that depended on it. I then extracted a `GeocoderResponse` class from these new methods so the `Geocoder` class is closer to what it was before.  The difference being that instead of returning the `Coordinates` object, it returns a `GeocoderResponse` object, which can be used to get the coordinates and location name.

Does this address your concerns above?

2025-01-21 21:35 UTC, mattstauffer approved these changes
Looks great!!

2025-01-21 21:36 UTC, mattstauffer commented
Wonderful work, great to merge @andrewmile!

2025-01-21 23:09 UTC, merged